### PR TITLE
Remove redundant files added in first commit

### PR DESCRIPTION
**Pull request by gwaybio**
These lab1 files are the same as the files @sklasfeld added in a previous commit. Organizing the repository by lab, rather than by content, would maintain focus and I think is a better organization strategy.

This PR removes these redundant files I added previously

### CODE REVIEW

**Comment by sklasfeld** [comment]
Where did you get these files? Were they from Raju? If so, were they edited in anyway from Sarah's slides? Maybe they are more updated and should replace the slides I put in lab1/py27.

**Comment by gwaybio** [comment]
I downloaded them directly from Piazza. Does that mean they are more recent?

**Comment by sklasfeld** [comment]
yeah and it looks like they are also in Python2.7 so maybe you should just replace the files I put in the py27 directory.

**Comment by gwaybio** [comment]
alright, i believe I replaced the files - look ok to you @sklasfeld ?

**Comment by sklasfeld** [comment]
Sorry, I must have been looking at the wrong files. These are in python3. Therefore, they just need to go in a new directory 'lab1/py3'. Sorry for the confusion. The rest of the stuff from Piazza should also go in py3 folders. I wasn't sure if Raju already made the switch in the first lecture. I guess she did.

**Comment by gwaybio** [comment]
yeah it does look like the jupyter kernel is using python 3, but the code written will only execute in python 2 - e.g. `print "what's", "up"` will not work in python 3. Perhaps instead it would be best to revert the kernel instead of moving the file.

**Comment by gwaybio** [comment]
next year this will not be an issue if #4 is completed and the course is run on Github

**Pull request closed without merging**
