### PR TITLE
Uploading most of Sarah's files as well as my own contributions

### PR DESCRIPTION
**Pull request by sklasfeld**
Sarah sent us her stuff at the beginning of the year. This is mostly everything. I also added the lectures that I edited.

### CODE REVIEW

**Comment by gwaybio** [comment]
This is comprehensive, thanks for getting the repo up to speed so quickly @sklasfeld 

Three general questions/comments:

1. I don't think we need to include dates in the file names. This is what version control is built for!
2. What is going on with the `withNotes` and `studentversion` files? Do we need both? I think it is best to reduce clutter.
3. A lot of the labs have data files. Thoughts on adding those files into their own respective `data` folder? For instance, in `python_bootcamp/lab4/`, `gene_expr.txt` can live in a `python_bootcamp/lab4/data/` folder. It may serve to clean up some of the larger folders and is easier to view as a new user.

**Comment by sklasfeld** [comment]
1. The dates are mostly because in 2016 we used python2.7 and therefore the slides and homeworks are made for python 2.7. On the other hand, in 2017 we used python3.
2. The "withNotes" just means the pdf has Sarahs notes at the bottom. The student version just means that it doesn't contain the slides with the answers on them for class. I thought it would be better if the students didn't already have the answered printed out in front of them when we asked class questions.
3. I find it easier to organize everything by the lab it comes from since the specific datasets are used in the respective lab. Therefore, I guess we could do `python_bootcamp/lab4/data/gene_expr.txt`. Is that what you mean?

**Comment by gwaybio** [comment]
> 1. The dates are mostly because in 2016 we used python2.7 and therefore the slides and homeworks are made for python 2.7. On the other hand, in 2017 we used python3.

Then I suggest scrapping all of the 2016 files - python 3 came out [almost 10 years ago](https://www.python.org/download/releases/3.0/) and [many of the early concerns](https://wiki.python.org/moin/Python2orPython3) have been addressed.

If 2.7 is still a large part of the course, then perhaps naming the files with py27 instead of 2016 would be more informative.

> Therefore, I guess we could do python_bootcamp/lab4/data/gene_expr.txt. Is that what you mean?

Yeah, that's what I mean - folders will help organization

**Comment by sklasfeld** [comment]
Let me know if that is okay.

**Comment by gwaybio** [comment]
LGTM - I like the renaming of the piazza posts to `README.md`

I will merge this in

**Comment by sklasfeld** [comment]
Thanks!

**Pull request merged**
